### ISSUE TITLE
[META] Crashing loading into the World Update 4

### ISSUE THREAD

**Issue by Sequal32** [Sequal32/yourcontrols#104]
Unfortunately there's nothing I can do to fix the crash. The update caused all addons/mods that use standalone WASM modules to crash the sim when loading in. We have to wait for a hotfix from Asobo.

**Comment by Sheetso** [comment]
I spent the half day disabling/enabling all mods I have (254) only to find out that yourcontrols is causing the crash....

**Comment by MarcusPred** [comment]
@Sheetso any 3rd party mod that has a modules folder inside them cause this crash. Yourcontrols is not the only addon doing this

**Comment by Sequal32** [comment]
Hotfix 1.15.8.0 fixes this issue!
