### ISSUE TITLE
[BUG] Flap 1 position

### ISSUE THREAD

**Issue by Road-to-Hell9** [Sequal32/yourcontrols#113]
**Describe the bug**
Flaps 1 position not synced

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.
2. Move flaps to 1

**Expected behavior**
The Flaps should be synced across all positions

**Additional context**
The other flap positions work

**__PLEASE ATTACH EVERYONE'S LOGS__**
[log.txt](https://github.com/Sequal32/yourcontrols/files/6479266/log.txt)

**Comment by OVI-7** [comment]
Had the same problem today, but it only happens on the ground. When flying it works perfectly

**Comment by Sequal32** [comment]
New release out (2.5.13) that address this.
