### ISSUE TITLE
[BUG] batteries not synced

### ISSUE THREAD

**Issue by OVI-7** [Sequal32/yourcontrols#114]
**Describe the bug**
Batteries buttons 1 and 2 not synced

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.
2. Push battery 1 or 2

**Expected behavior**
Batteries should work for both PF and PM

**__PLEASE ATTACH EVERYONE'S LOGS__**
[log.txt](https://github.com/Sequal32/yourcontrols/files/6481313/log.txt)e file`

**Discord**
ovi_7#8815

**Comment by Sequal32** [comment]
New release out (2.5.13) that address this.
