### ISSUE TITLE
[BUG] PM can't rotate stab trim (THS)

### ISSUE THREAD

**Issue by OVI-7** [Sequal32/yourcontrols#115]
**Describe the bug**
PF can rotate but PM can't rotate stab trim wheel (THS)

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.
2. PM: try to rotate stab trim

**Expected behavior**
Trim should be rotated by both PF or PM

**__PLEASE ATTACH EVERYONE'S LOGS__**
[log.txt](https://github.com/Sequal32/yourcontrols/files/6481327/log.txt)

**Discord**
ovi_7#8815

**Comment by Sequal32** [comment]
New release out (2.5.13) that address this.
