### ISSUE TITLE
[BUG] PM doesn't see flight controls movement on ECAM

### ISSUE THREAD

**Issue by OVI-7** [Sequal32/yourcontrols#116]
**Describe the bug**
When PF performs flight controls check PM doesn't see any movement on ECAM.
PM can see the movements of side stick, pedals. Only ECAM doesn't show the movements.

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.
2. Start your aircraft, select F\CTL page on ECAM
3. Perform flight controls check

**Expected behavior**
PM should see flight controls movements on ECAM

**__PLEASE ATTACH EVERYONE'S LOGS__**
[log.txt](https://github.com/Sequal32/yourcontrols/files/6481355/log.txt)

**Discord**
ovi_7#8815

**Comment by Sequal32** [comment]
New release out (2.5.13) that address this.
