### ISSUE TITLE
[BUG] FCU not synced

### ISSUE THREAD

**Issue by IamLuisAUT** [Sequal32/yourcontrols#118]
**Describe the bug**
All Knobs on the FCU are not synchronised (not turning at all).

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Connect with A20NX
2. Get in the air
3. Turn knobs on the FCU

**Expected behavior**
The knobs on the other side of the connection are turning synchronised.

**Additional context**
Pushing or pulling does work.

**__PLEASE ATTACH EVERYONE'S LOGS__**
[log.txt](https://github.com/Sequal32/yourcontrols/files/6526433/log.txt)

**Discord**
IamLuis#4140

**Comment by IamLuisAUT** [comment]
Addition: Its only on Experimental-Version of the FBW.

**Comment by Sequal32** [comment]
Do you mean development version? The FCU should sync well if the knobs aren't on managed mode.

**Comment by IamLuisAUT** [comment]
With the newest Dev Version everything is looking good, except the Speed Knob is not synced.
