### ISSUE TITLE
[BUG] A32NX Seatbelts Signs not synced

### ISSUE THREAD

**Issue by SierraBravo1** [Sequal32/yourcontrols#119]
**Describe the bug**
The A32NX (dev) Seatbelts Signs are not synced.

**To Reproduce**
1. Start as server or client.
2. Switch the seatbelt signs.
3. Observe seatbelts switch and ecam notification at server and client.

**Expected behavior**
Seatbelts should be synced

**Comment by Sequal32** [comment]
Thanks! Fixed in 2.5.14.
