### ISSUE TITLE
A320NX Inop[BUG]

### ISSUE THREAD

**Issue by Road-to-Hell9** [Sequal32/yourcontrols#123]
**Describe the bug**
The A320NX no longer works, important features like battery and ADIRS no longer synced and others like ECAM pages and Lights

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.

**Expected behavior**
Normal behaviour

**__PLEASE ATTACH EVERYONE'S LOGS__**
[log.txt](https://github.com/Sequal32/yourcontrols/files/6587669/log.txt)

Discord User:
Homer#0187

**Comment by Sequal32** [comment]
Have you tried this again and still the same result? It seems to work fine for other people.

**Comment by Road-to-Hell9** [comment]
Sorry, only happened once
