### ISSUE TITLE
A320 TO Parking Brake[BUG]

### ISSUE THREAD

**Issue by Road-to-Hell9** [Sequal32/yourcontrols#124]
**Describe the bug**
On the A320 the parking brake gets set on the copilot's side on takeoff, this only results in a master warning and not stoping the aircraft because it doesn't sync the action of setting the brakes

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start server
2. Connect
3. Set up for takeoff
4. Set thrust to TO/GA

**__PLEASE ATTACH EVERYONE'S LOGS__**
[Logs.zip](https://github.com/Sequal32/yourcontrols/files/6626168/Logs.zip)

**Discord**
Homer#0187

**Comment by Sequal32** [comment]
Fixed in version 2.5.16, thanks!
