### ISSUE TITLE
[Request]Just Flight PA28 Arrow turbo

### ISSUE THREAD

**Issue by pacha35** [Sequal32/yourcontrols#126]
Hi,
do you plan to include the PA28 Arrow IV Tubo from Just Flifght in the list of the aircrafts synced ?
Thanks for the very useful mod

Pacha 35

**Comment by Sequal32** [comment]
Hopefully in the future!

**Comment by rthom91** [comment]
If you are in the discord, Warrior support has been added in the latest release candidate.
