### ISSUE TITLE
[New Request] PMDG DC-6 Support Please

### ISSUE THREAD

**Issue by Platohjwang** [Sequal32/yourcontrols#128]
As the Topic

**Comment by Flusinerd** [comment]
+1

**Comment by AndreGeddert** [comment]
i would love this! +1

**Comment by Sequal32** [comment]
I'm personally waiting until I get the rewrite (v3) done before looking into this, but one of the people in the discord server seems to be making good progress.

**Comment by vorden44** [comment]
I'd buy the DC-6 if it had multicrew.

**Comment by AndreGeddert** [comment]
> I'd buy the DC-6 if it had multicrew.

its worth its money even without that, but would be a dream with multicrew. Message me when it got multicrew, so we can fly together :)

**Comment by rthom91** [comment]
DC-6 (beta profile) added in 2.6.1.
