### ISSUE TITLE
[BUG] Gear lever not syncing (A32NX Dev)

### ISSUE THREAD

**Issue by jpccaldas** [Sequal32/yourcontrols#130]
**Describe the bug**
The gear lever is not syncing on A32NX Dev, both latest version (YourControls and A32NX Dev).

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.
2. Client joins.
3. Depart, use gear lever.

**Expected behavior**
It is supposed to lift the gear up/down.

**__PLEASE ATTACH EVERYONE'S LOGS__**
Log Host: [log.txt](https://github.com/Sequal32/yourcontrols/files/6839626/log.txt)
Log Client: [log.txt](https://github.com/Sequal32/yourcontrols/files/6839630/log.txt)

**Discord**
jpccaldas#8164

**Comment by FGouveia13** [comment]
Can confirm this bug exists, on the dev version of 18.07.2021

**Comment by Samueleonard** [comment]
i did a flight yesterday on the latest dev version and they synced fine

**Comment by jpccaldas** [comment]
> i did a flight yesterday on the latest dev version and they synced fine

Last version of YourControls too (2.5.17)?

**Comment by Samueleonard** [comment]
> Last version of YourControls too (2.5.17)?

yep

**Comment by jpccaldas** [comment]
Disregard. Tested now and worked... Who knows...
