### ISSUE TITLE
"End Flight" Menu on Observer at Touchdown

### ISSUE THREAD

**Issue by aparsons671** [Sequal32/yourcontrols#132]
Just bought a second copy of MSFS for a reverse in-the-cockpit view with my webcam green-screened and superimposed on the rear-facing view of computer #2 while flying on computer #1.  As soon as I touched down, the stupid "end flight" menu popped up on computer #2 set up as the observer.  As I understand it, this is due to the engine combustion flag not set, as on the main computer, whenever I cut the mixture to the engines, it pops up on computer #1.  Any insight on addressing this would be appreciated.

MSFS 1.18.14.0 (SU5+Hotfix)
YC 2.5.18
Carenado Piper PA34T Seneca V

**Comment by aparsons671** [comment]
second flight resulted in end flight screen when i stopped on the ramp (did not stop from touchdown to arrival at parking)...engines still running and electrics on.  main computer end flight screen popped at mixture cutoff, as normal.

**Comment by rthom91** [comment]
The Seneca V isn't officially supported yet.

**Comment by rthom91** [comment]
Seneca V added in 2.6.1.
