### ISSUE TITLE
Sync Time

### ISSUE THREAD

**Issue by aparsons671** [Sequal32/yourcontrols#133]
It would be great to sync the time via the protocol, that way as I'm flying if I change the time on the server, the client will be updated as well.  Live weather will be the only option that is feasible since the weather data cannot be synced across the sims to my knowledge.

update: added software versions for reference

MSFS 1.18.14.0
YC 2.5.18

**Comment by rthom91** [comment]
It is, or at least should be the moment client connects to server.

**Comment by aparsons671** [comment]
nope...running it right now...

set observer to daytime, server to night time....no change on observer

disconnected observer and reconnected, no change
stopped server, restarted and reconnected observer, no change

**Comment by JasonO99** [comment]
I cannot reproduce this. As explained, the time syncs a point of connection with the host for me. Reproduction steps by OP seem to be quite straight forward, so I suspect this has been fixed since July 2021.
