### ISSUE TITLE
[BUG]A32NX (dev) Frequencies keep switching randomly if non-hoster make input on flighttab

### ISSUE THREAD

**Issue by karel1710** [Sequal32/yourcontrols#136]
During the flight frequencies keep switching around without any reason, if the frequency was choosen by the non-host player on the flight tab. 

If all inputs are done as hoster than it seems to be stable.
Really annoying if flying on vatsim. 

I cant determine if its the flighttab or if it would also appear if 2nd player do change the frequency

**Comment by MrMinimal** [comment]
I have the same problem in the FBW A320 as a client when switching into external view and going back into the cockpit.
But I have no idea what a flighttab is.

**Comment by John-UK** [comment]
Someone has AI assistance is the most likely cause. Switch off all assistance options in MSFS.

**Comment by MrMinimal** [comment]
Found a fix. The reason was NOT AI (though it often is). The default keyboard mapping for "select ATC option" 1-9 are on the number keys.
So were my view presets.

I had to unassign all ATC select options for it to not happen again.
