### ISSUE TITLE
Client disconnected. Reason: No message received from the server.

### ISSUE THREAD

**Issue by IndibarDutta** [Sequal32/yourcontrols#138]
**I am trying to play MFS2020 with my brother using YourControls. We had chosen Airbus A320neo the default plane given in the game. When we are in cockpit and when I am creating a session he is not able to join. He is getting this error. When he is hosting the server and when I am trying to join I am also getting the same error. We both are getting the same error message. Please help me with this issue as too how can I solve this... I am not able to play because of this. We both have selected the same airports same settings multiplayer off but still it is happening. Please help me please!**

**Comment by AndreGeddert** [comment]
@IndibarDutta please give more information on how you connect

- Which method? direct, p2p oder cloud-server?
- Did you check your local windows firewalls?
- If direct method, did you use UPNP? If UPNP is not supported or enabled, did you forward port 25071/udp in your router to you sim-maschine?

**Comment by BalaBalaYi** [comment]
same problems... already shutdown all the firewall but still failed.

**Comment by su4n** [comment]
L
