### ISSUE TITLE
[BUG] FBW A32NX Dev. - Arming of Spoilers is not synced

### ISSUE THREAD

**Issue by SierraBravo1** [Sequal32/yourcontrols#142]
**Describe the bug**
Arming of Spoilers is not synced at FBW A32NX Development with Your Controls V2.6.0.

**To Reproduce**
1. Start a session with FBW A32NX.
2. In Control: Arm Spoilers.
3. Client: Check if spoilers are armed, too.

**Expected behavior**
Arming of Spoilers is synced between all clients.

**Comment by rthom91** [comment]
Patched in next release. Temporary update can be found in changelog channel on discord.

**Comment by Sequal32** [comment]
Fixed as of 2.6.1
