### ISSUE TITLE
[BUG] Taking control using joystick no longer works

### ISSUE THREAD

**Issue by foxmike80** [Sequal32/yourcontrols#143]
**Describe the bug**
Switching control using the toggle launch bar switch function no longer works in YC 2.6.

**To Reproduce**
1. Start as client.
2. Try to take control from server by pressing the joystick button assigned to "toggle launch bar switch"

**Expected behavior**
Client should take control from server.

**Additional context**
Did work in the last version before 2.6.

**Discord**
foxmike1080

**Comment by rthom91** [comment]
Patched in next release. Temporary update can be found in changelog channel on discord.

**Comment by Sequal32** [comment]
Fixed as of 2.6.1
