### ISSUE TITLE
Doesn't work and puts connected

### ISSUE THREAD

**Issue by Arnauta2** [Sequal32/yourcontrols#145]
**Describe the bug**
Me and my friend are conecting by your controls, the it puts connected but it doesn't work. We can't sync any buttpm [BUG]

**To Reproduce**
1.Start server
2.Connect

**Expected behavior**
It has to be able to touch all buttons and all things on the cockpit
**Additional context**

**__PLEASE ATTACH EVERYONE'S LOGS__**
`Log.txt` can be found in the directory of the .exe file`[log.txt](https://github.com/Sequal32/yourcontrols/files/7446978/log.txt)
14:48:49 [WARN] [PROGRAM] Could not open config. Using default values. Reason: El sistema no puede encontrar el archivo especificado. (os error 2)
14:48:49 [INFO] [DEFINITIONS] Found 43 configuration file(s).
14:48:50 [INFO] [UPDATER] Version 2.6.0 in use, 2.6.0 is newest.
14:49:16 [INFO] [SIM] Connected to SimConnect.
14:49:16 [INFO] [NETWORK] Listening on Ok(0.0.0.0:50761)
14:49:16 [INFO] [NETWORK] Client started.
14:49:16 [INFO] [NETWORK] Sent packet to port 1818. Retry #1
14:49:16 [INFO] [NETWORK] Established connection with port 1818 on !
14:49:16 [INFO] [NETWORK] wwww connected. In control: true, observing: false, server: true
14:49:22 [INFO] [PACKET] AllNeedSync { avars: {}, lvars: {"L:Generic_Master_Caution_Active": 0.0}, events: [] }
14:49:22 [INFO] [PACKET] AllNeedSync { avars: {}, lvars: {}, events: [JSEvent { name: "H:YCHGeneric_Master_Caution_Push" }] }
14:49:22 [INFO] [PACKET] AllNeedSync { avars: {}, lvars: {"L:Generic_Master_Warning_Active": 0.0}, events: [JSEvent { name: "H:YCHGeneric_Master_Warning_Push" }] }
14:49:45 [INFO] [PACKET] AllNeedSync { avars: {"LIGHT STROBE:1": F64(0.0), "GENERAL ENG MASTER ALTERNATOR:2": I32(0), "CIRCUIT ON:28": Bool(false), "LIGHT BEACON:1": F64(0.0), "KOHLSMAN SETTING MB:1": F64(16212.0), "MARKER SOUND:1": F64(1.0), "CIRCUIT GENERAL PANEL ON": Bool(false), "GENERAL ENG FUEL VALVE:2": Bool(true), "BRAKE PARKING POSITION": Bool(true), "EXTERNAL POWER ON:1": Bool(false), "TRANSPONDER STATE:1": I32(0), "CIRCUIT SWITCH ON:52": Bool(false), "TRANSPONDER CODE:1": I32(0), "TURB ENG IGNITION SWITCH EX1:2": I32(0), "KOHLSMAN SETTING MB:2": F64(16212.0), "CIRCUIT ON:29": Bool(false), "AUTOPILOT FLIGHT DIRECTOR ACTIVE:1": Bool(false), "CIRCUIT ON:27": Bool(false), "AUTOPILOT YAW DAMPER": Bool(false), "GENERAL ENG MASTER ALTERNATOR:1": I32(0), "TURB ENG IGNITION SWITCH EX1:1": I32(0), "GENERAL ENG FUEL VALVE:1": Bool(true), "AUTOPILOT DISENGAGED": I32(0), "ELECTRICAL MASTER BATTERY:1": Bool(false), "AUTOPILOT ALTITUDE LOCK": Bool(false), "LIGHT PANEL:1": I32(0), "ELT ACTIVATED": Bool(false), "CIRCUIT SWITCH ON:26": Bool(false), "LIGHT LOGO:1": F64(0.0), "AUTOPILOT ALTITUDE LOCK VAR:1": I32(0), "AUTOPILOT ALTITUDE LOCK VAR:3": I32(0), "RUDDER TRIM PCT": I32(0)}, lvars: {}, events: [] }
14:49:45 [INFO] [PACKET] AllNeedSync { avars: {}, lvars: {"L:AS3X_Touch_2_State": 0.0, "L:Condition_Lever_CutOff_1": 1.0, "L:PFD_CDI_Source": 0.0, "L:LIGHTING_POTENTIOMETER_3_Power_Setting": 0.0, "L:AS3X_Touch_Brightness_Auto": 0.0, "L:LIGHTING_STROBE_1": 0.0, "L:AS3X_Touch_1_ScreenLuminosity": 0.0, "L:XMLVAR_ELT_TEST_TIME": 0.0, "L:LIGHTING_POTENTIOMETER_6_Power_Setting": 0.0, "L:XMLVAR_ELT_ACTIVATION_TIME": 0.0, "L:AS3X_Touch_1_State": 0.0, "L:LIGHTING_POTENTIOMETER_11": 0.0, "L:AS3X_Touch_Brightness": 0.0, "L:MFD_MapZoomRange": 0.0, "L:XMLVAR_Starter1": 0.0, "L:GPS_Current_Phase": 0.0, "L:Condition_Lever_CutOff_2": 1.0, "L:LIGHTING_PANEL_1": 0.0, "L:Glasscockpit_DmeSource": 0.0, "L:LIGHTING_POTENTIOMETER_5_Power_Setting": 0.0, "L:LIGHTING_POTENTIOMETER_4_Power_Setting": 0.0, "L:HANDLING_RudderTrim": 0.0, "L:AS3X_Touch_2_ScreenLuminosity": 0.0, "L:DigitalOAT_State": 0.0, "L:LIGHTING_POTENTIOMETER_10": 0.0, "L:HourMeter_ScreenLuminosity": 0.0, "L:ParkingBrake_Position": 100.0, "L:HourMeter_State": 0.0, "L:AS1000_Warnings_Master_Set": 0.0, "L:LIGHTING_LOGO_1": 0.0, "L:AS3X_Touch_Brightness_IsAuto": 0.0, "L:LIGHTING_BEACON_1": 0.0, "L:XMLVAR_Starter2": 0.0, "L:MFD_Main_MapZoomRange": 0.0, "L:ELECTRICAL_ExternalPower_1": 0.0, "L:DigitalOAT_ScreenLuminosity": 0.0, "L:XMLVAR_ELT_STATE": 0.0}, events: [] }
14:51:28 [ERROR] Encountered an error receiving data: Os { code: 10054, kind: ConnectionReset, message: "Se ha forzado la interrupción de una conexión existente por el host remoto." }
14:51:29 [ERROR] Encountered an error receiving data: Os { code: 10054, kind: ConnectionReset, message: "Se ha forzado la interrupción de una conexión existente por el host remoto." }
14:51:31 [ERROR] Encountered an error receiving data: Os { code: 10054, kind: ConnectionReset, message: "Se ha forzado la interrupción de una conexión existente por el host remoto." }
14:51:31 [WARN] Dropping connection because there were no packets received for 3 seconds.
14:51:31 [INFO] [NETWORK] Server/Client stopped. Reason: No message received from server.

**Discord**
Arnauta
[log.txt](https://github.com/Sequal32/yourcontrols/files/7446978/log.txt)
.

**Comment by rthom91** [comment]
Please try reinstalling.
https://github.com/sequal32/yourcontrolsinstaller/releases/latest/download/installer.zip
