### ISSUE TITLE
 Request]Just Flight PA28 Warrior II 

### ISSUE THREAD

**Issue by JayceFlight** [Sequal32/yourcontrols#150]
Hi,
do you plan to include the "PA28 PA28 Warrior II" from Just Flifght in the list of the aircrafts synced ?
Thanks for the very useful mod

**Comment by milhouz** [comment]
Just a heads up not sure if you saw the main readme but project is currently on hiatus.

**Comment by rthom91** [comment]
If you are in the discord, Warrior support has been added in the latest release candidate.
