### ISSUE TITLE
[Request] PMDG 737-700

### ISSUE THREAD

**Issue by yoav180** [Sequal32/yourcontrols#154]
I'm pretty sure someone's already working on this, but you know, just in case...

**Comment by entangledion** [comment]
This! I was surprised it wasn’t already in the list

**Comment by crodell2** [comment]
I'm sure they wouldn't be left out, but bump to include the 600 and 800

**Comment by mlawson1217** [comment]
Double bump. Hope it includes the 600, 700, and 800. Hopefully the customizable cockpit doesn't cause issues but if it does, even a mandatory aircraft setup for compatibility would work fine.

**Comment by DanielGiurgiuman** [comment]
TIPLE BUMP FOR 800 :)

**Comment by argi001** [comment]
+1 for 800 or 700

**Comment by hallonmunken** [comment]
+1 for -800

**Comment by ajmallek** [comment]
+1 as well

**Comment by diogorocha18** [comment]
+1 também

**Comment by diogorocha18** [comment]
+1 as well please

**Comment by yoav180** [comment]
@Sequal32 It's been a while since the PMDG 737s were released. Are these planes in the road-map?
Thanks!!

**Comment by rthom91** [comment]
Added 2.7.6. See notes.
