### ISSUE TITLE
fly by wire Nav issue

### ISSUE THREAD

**Issue by kekev2001** [Sequal32/yourcontrols#155]
![Schermafbeelding 2022-05-28 140224](https://user-images.githubusercontent.com/56051728/170824665-3942181e-2e18-4c31-8aa9-889660187f38.png)
![Schermafbeelding 2022-05-28 140251](https://user-images.githubusercontent.com/56051728/170824667-667b635e-3450-4490-8ac5-85c3d56fb9b4.png)

Flybywire Nav bug 
when a friend is inporting the route he gets the route completly 
only when he does thats i see no route

**Comment by celi28** [comment]
You need to also have the dispatch on simbrief.

**Comment by Sequal32** [comment]
Make sure you have the same simbrief username set in the MCDU.
