### ISSUE TITLE
Can you add an option for add another airplane ?

### ISSUE THREAD

**Issue by Jules010209** [Sequal32/yourcontrols#158]
For example add a button and if we click on it, we can add a plane and play with our friends in this plane ?

**Comment by rthom91** [comment]
That's not at all how the application works. This route would (mostly) work when sharing the default Asobo aircraft which are simplified. Any 3rd-party aircraft or mod requires their own specific profile, which requires thorough testing before publishing.

**Comment by Jules010209** [comment]
Ok, thanks for the information, good evening.
