### ISSUE TITLE
MCP SPD/HDG/VS keeps resetting when adjusting MCP (A32NX [v54b8571] DEV/STABLE) 

### ISSUE THREAD

**Issue by MikelFernandes** [Sequal32/yourcontrols#172]
**Describe the bug**
MCP SPD/HDG/VS keeps resetting when adjusting on the MCP (A32NX [v54b8571] DEV/STABLE) 

**To Reproduce**
In the clips you can see that when I adjust the MCP knobs the value auto resets. In the video I am only scrolling or draging UP so if you see the value going down it's not me (that is the bug). The ALT value doesn't seem to be affected by this bug only SPD/HDG/ALT and V/S. This bug isn't present when offline. Video evidence: https://streamable.com/stax1y https://streamable.com/jr9o4l https://streamable.com/6vtz15 https://streamable.com/u72il5 

**Expected behavior**
I expect the values not to reset/de-sync. 

We tested and the bug happens on 10/40/60 Update Rate and on the Cloud Server/Cloud Host. We didn't test other settings but I am sure it's also present there. The slower you move the knob the higher the chance is that it will reset/de-sync.

**Discord**
MikelF#3060, JeremyXP#6140
[log (1).txt](https://github.com/Sequal32/yourcontrols/files/9739780/log.1.txt)
[log.txt](https://github.com/Sequal32/yourcontrols/files/9739781/log.txt)

**Comment by rthom91** [comment]
Should be fixed in new update.

**Comment by rthom91** [comment]
Update is available.

**Comment by JasonO99** [comment]
This occurred frequently with friend and I on the update that I think introduced the bug. Flights since the update a few days ago I have not had a single issue.

**Comment by rthom91** [comment]
Was this fixed for you in 2.6.4?
