### ISSUE TITLE
SimConnect exception occurred: 1&3 - connected but nothing happends. 

### ISSUE THREAD

**Issue by matsbrende** [Sequal32/yourcontrols#175]
**Describe the bug**
SimConnect exception occurred: 3 & 1
We are connected and log is produced
Simulator does not replicate actions as seen in the log
In this case, lights

**To Reproduce**
Loads aircraft
Server running
I connect to the server
Log is updates with events but simulator does not replicate
Then I am given control
SimConect exception occured: 3&1
No more events are described until control is taken back

**Expected behavior**
Buttons to sync when log events are happening

**Additional context**

**__PLEASE ATTACH EVERYONE'S LOGS__**
22:17:12 [INFO] [DEFINITIONS] Found 94 configuration file(s).
22:17:13 [INFO] [UPDATER] Version 2.7.3 in use, 2.7.3 is newest.
22:17:17 [INFO] [SIM] Connected to SimConnect.
22:17:17 [INFO] [NETWORK] Listening on Ok(0.0.0.0:51757)
22:17:17 [INFO] [NETWORK] Client started.
22:17:18 [INFO] [NETWORK] Listening on Ok(0.0.0.0:51759)
22:17:18 [INFO] Sending request to port 5571 to join session
22:17:18 [INFO] [NETWORK] New client started to connect to hosted server.
22:17:18 [INFO] [NETWORK] Sent packet to port 5571. Retry #1
22:17:18 [INFO] [NETWORK] Established connection with port 5571 on LECLHYXA!
22:17:18 [INFO] [NETWORK] ruben connected. In control: true, observing: false, server: false
22:17:22 [INFO] [NETWORK] Request to disconnect.
22:17:22 [INFO] [NETWORK] Server/Client stopped. Reason: Stopped.
22:17:29 [INFO] [SIM] Connected to SimConnect.
22:17:29 [INFO] [NETWORK] Listening on Ok(0.0.0.0:61236)
22:17:29 [INFO] [NETWORK] Client started.
22:17:29 [INFO] [NETWORK] Listening on Ok(0.0.0.0:61238)
22:17:29 [INFO] Sending request to port 5571 to join session
22:17:29 [INFO] [NETWORK] New client started to connect to hosted server.
22:17:29 [INFO] [NETWORK] Sent packet to port 5571. Retry #1
22:17:29 [INFO] [NETWORK] Established connection with port 5571 on LECLHYXA!
22:17:29 [INFO] [NETWORK] ruben connected. In control: true, observing: false, server: false
22:17:45 [INFO] [CONTROL] Server set us to observing? true
22:17:52 [INFO] [PACKET] AllNeedSync { avars: {"LIGHT CABIN:1": I32(0)}, lvars: {"L:LIGHTING_CABIN_1": F64(0.0)}, events: [] }
22:17:58 [INFO] [PACKET] AllNeedSync { avars: {"LIGHT CABIN:1": I32(1)}, lvars: {"L:LIGHTING_CABIN_1": F64(1.0)}, events: [] }
22:18:02 [INFO] [PACKET] AllNeedSync { avars: {"LIGHT TAXI:1": F64(1.0)}, lvars: {}, events: [] }
22:18:02 [INFO] [PACKET] AllNeedSync { avars: {}, lvars: {"L:LIGHTING_TAXI_1": F64(1.0)}, events: [] }
22:18:06 [INFO] [PACKET] AllNeedSync { avars: {"LIGHT STROBE:1": F64(0.0)}, lvars: {}, events: [] }
22:18:06 [INFO] [PACKET] AllNeedSync { avars: {}, lvars: {"L:LIGHTING_STROBE_1": F64(0.0)}, events: [] }
22:18:07 [INFO] [PACKET] AllNeedSync { avars: {"LIGHT STROBE:1": F64(1.0)}, lvars: {}, events: [] }
22:18:07 [INFO] [PACKET] AllNeedSync { avars: {}, lvars: {"L:LIGHTING_STROBE_1": F64(1.0)}, events: [] }
22:18:12 [INFO] [PACKET] AllNeedSync { avars: {"BRAKE PARKING POSITION": I32(0)}, lvars: {}, events: [] }
22:18:12 [INFO] [PACKET] AllNeedSync { avars: {}, lvars: {"L:ParkingBrake_Position": F64(0.0)}, events: [] }
22:19:11 [INFO] [CONTROL] Server set us to observing? false
22:19:11 [INFO] [CONTROL] Taking control from ruben
22:19:11 [WARN] [SIM] SimConnect exception occurred: 1
22:19:11 [WARN] [SIM] SimConnect exception occurred: 1
22:19:11 [WARN] [SIM] SimConnect exception occurred: 1
22:19:11 [WARN] [SIM] SimConnect exception occurred: 3
22:19:11 [WARN] [SIM] SimConnect exception occurred: 3
22:20:06 [INFO] [CONTROL] ruben is now in control.
22:20:06 [WARN] [SIM] SimConnect exception occurred: 1
22:20:06 [WARN] [SIM] SimConnect exception occurred: 1
22:20:06 [WARN] [SIM] SimConnect exception occurred: 1
22:20:06 [WARN] [SIM] SimConnect exception occurred: 3
22:20:06 [WARN] [SIM] SimConnect exception occurred: 3
22:20:18 [INFO] [PACKET] AllNeedSync { avars: {"AVIONICS MASTER SWITCH:1": I32(0), "CIRCUIT AVIONICS ON": Bool(false)}, lvars: {}, events: [] }
22:20:18 [INFO] [PACKET] AllNeedSync { avars: {"AVIONICS MASTER SWITCH:1": I32(1)}, lvars: {}, events: [] }
22:20:18 [INFO] [PACKET] AllNeedSync { avars: {"CIRCUIT AVIONICS ON": Bool(true)}, lvars: {}, events: [] }
22:20:24 [INFO] [NETWORK] Request to disconnect.
22:20:24 [INFO] [NETWORK] Server/Client stopped. Reason: Stopped.

**Discord**
Your discord name if you're in the YourControl discord server.

**Comment by rthom91** [comment]
Are you running a VPN?

**Comment by matsbrende** [comment]
> Are you running a VPN?

No VPN connection

**Comment by rthom91** [comment]
I probably need to troubleshoot this over Discord with you both. Chances are yours or friends connection is restrictive.

**Comment by matsbrende** [comment]
Just let me know if you have time :) Thank you

**Comment by rthom91** [comment]
> Just let me know if you have time :) Thank you

What is your Discord name?

**Comment by rthom91** [comment]
Assuming this has been sorted. Potentially with a program reinstallation or disabling of firewalls. If the problem still exists when connection using Direct, your ISP might be restrictive or your router needs settings changed. 25071 UDP is the port that should be open/allowed.
