### ISSUE TITLE
[BUG] A32NX development bug

### ISSUE THREAD

**Issue by leezhiwei** [Sequal32/yourcontrols#177]
**Describe the bug**
When flying the A32NX, we had a few issues with development, firstly, the radios from my co-pilot and mine did not sync, his was at 122.550. Secondly, after take-off his flight sim just froze, while mine continued. Even after our thrust levers are synced to FLX MCT, his PFD does not show MAN FLX

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.
2. Do a flight
3. Then encounter the error when syncing flight

**Expected behavior**
A clear and concise description of what you expected to happen. For example: Navigation lights are synced between all clients.
For all aspects to be synced and working well with my copilot

**Additional context**

**__PLEASE ATTACH EVERYONE'S LOGS__**
`Log.txt` can be found in the directory of the .exe file`
[log-copilot.txt](https://github.com/Sequal32/yourcontrols/files/9844694/log-copilot.txt)

**Discord**
Your discord name if you're in the YourControl disc
[log - Captain.txt](https://github.com/Sequal32/yourcontrols/files/9844679/log.-.Captain.txt)
ord server.

**Comment by leezhiwei** [comment]
Additionally both of our MCDUs. In the INIT A page, the Flight Number field is also not synced when SimBrief flight plan is used.

**Comment by leezhiwei** [comment]
Hello?

**Comment by alexandresebrao** [comment]
I'm having also problems with A20NX like SPD going to 100 and HDG to 000, also fmc wont configure arrival and approach

**Comment by JasonO99** [comment]
Are these issues still a problem since 2.7.4?

> I'm having also problems with A20NX like SPD going to 100 and HDG to 000, also fmc wont configure arrival and approach

This issue with the AP knobs was fixed in 2.7.3. I've not had any issues with configuring the arrival/approaches. Are you saying it doesn't work at all, or just doesn't sync? Make sure all pilots are looking at the MCDU when operating it as it seems to not sync button presses everytime when you're not looking at.



> Additionally both of our MCDUs. In the INIT A page, the Flight Number field is also not synced when SimBrief flight plan is used. Basically his MCDU is orange boxes while mine is filled in blue.

Is everyone loading the OFP from the same SimBrief username in the EFB?

**Comment by leezhiwei** [comment]
I will update soon, haven't really got time to play flight sim.

**Comment by leezhiwei** [comment]
Perfectly working with my partner! Great job and thank you.
