### ISSUE TITLE
[REQUEST] Black Square Steam Gauge Overhaul for MSFS King Air 350i

### ISSUE THREAD

**Issue by TalonActual** [Sequal32/yourcontrols#178]
Not sure if this is something anyone else would like to see, but it’s an excellent mod that would be greatly enhanced by the ability to share workload.

**Comment by TalonActual** [comment]
Not sure if this is something anyone else would like to see, but it’s an excellent mod that would be greatly enhanced by the ability to share workload.

**Comment by rthom91** [comment]
Added 2.7.9.
