### ISSUE TITLE
Working Title CJ4 Flight Computer de-sync issues

### ISSUE THREAD

**Issue by jrob** [Sequal32/yourcontrols#190]
Working title CJ4 v0.12.14

YourControls v2.7.4

While flying tonight we tested out YourControls. Most things went very well. Very impressive. There were a few things that did cause problems. The other pilot is more experienced, while I am learning. If I had been actively trying to assist in the flight by making flight plan changes I may have cause problems. Since he was making the changes, we didn't really run into issues. 

We were able to capture some screen shots that show the synchronization issues we encountered.

flight director not in sync. This screenshot is not very pronounced but a few mins before it was much more obvious.

![image](https://user-images.githubusercontent.com/613402/210467660-ddcafccf-3f81-4869-a226-a16226af2585.png)

![image](https://user-images.githubusercontent.com/613402/210469397-e481f09c-44d3-4eb1-a83d-34529d6be4f8.png)

Navigation scale. This came back in sync and I believe it was because we zeroed it out which put them back in sync.

![image](https://user-images.githubusercontent.com/613402/210469296-8c0c2e3c-3cbf-4187-a8af-edc2856c7425.png)

![image](https://user-images.githubusercontent.com/613402/210469378-0ff58976-e8f8-4d82-bde5-bccb581dcd28.png)

Flight plan. This was initally completely out of sync which resolved itself and then drifted again. Below you can see the waypoints in pink are not the same.

![image](https://user-images.githubusercontent.com/613402/210472145-87e9c2f5-2d26-48e6-ab3a-fc0e24bb785c.png)

![image](https://user-images.githubusercontent.com/613402/210472164-b3225e6d-2a89-4ba9-a8d1-49eb9a540251.png)

Vatsim filing in case it is useful.

![image](https://user-images.githubusercontent.com/613402/210477828-26c43503-e644-46fb-8ebf-7fdede1ce577.png)

**Comment by rthom91** [comment]
We're you both running the exact same navdata?

**Comment by jrob** [comment]
The nav data was put in my friend. I didn't do any nav. It was wonky at first, but then seemed to sync up fine. It was only later that things got weird. It was really him doing the flying and me along for the ride. In the future we would like to do division of labor so I spent a fair bit of time looking for inconsistencies that would make that difficult.

**Comment by rthom91** [comment]
If only one of you has navigraph installed or you have an outdated version, the routes will not sync correctly when implemented.

**Comment by jrob** [comment]
We had the same issue with a cessna 172 g1000 yesterday. We have the same navdata from navigraph. Is the button presses the only thing being synced? Or is the state of the g1000 being synced? It seems as tho it's only the key presses which don't always get sent correctly.

**Comment by JasonO99** [comment]
> 

Unless the information is stored in a variable that can be read and set by YourControls (and configured as such in the definitions), then it's the button presses that are synced as far as I am aware. At least it is with other aircraft. If you manually input the flight plan and one button doesn't sync then every subsequent button press will be on a different page or stage and go wrong.

**Comment by rthom91** [comment]
As long as you both have the EXACT same navdata installed, everything should sync up as long as you don't breeze through the key inputs. For aircraft like the CJ4 with an FMC it's best to just download the flight plan from simbrief so you don't have to worry about any key presses not syncing fast enough.
