### ISSUE TITLE
A320 FBW and ASOBO  sharing  [BUG]

### ISSUE THREAD

**Issue by NICOMIF** [Sequal32/yourcontrols#201]
Hello sir,
We have a trouble with the version 2.7.5 with FBW and ASOBO.
One of the aircraft shared is in the air (2 meters) over the ground or under the ground (2 meters) on depending who is the master sharing.
Before this version, we have no trouble...
Thanks to you.
Regards
Nicolas and Francis

**Comment by JasonO99** [comment]
This will be a scenery issue. Either one of you doesn't have the updated world update or custom scenery being used.
