### ISSUE TITLE
PMDG AP soft disengage doesn't work

### ISSUE THREAD

**Issue by o4oren** [Sequal32/yourcontrols#208]
**Describe the bug**
Disengage AP with the event "Yoke Left Autopilot Disengage" fails to propagate to the other client.
We tried different mappings to the soft disengage button, it seems that only a physical press of the CMD button or Disengage bar with the mouse works.

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. connect a pair of instances with PMDG.
2. start a flight and engage AP
3. The controlling pilot uses the soft disengage button - the other side is not disconnected.

**Expected behavior**
Soft disengage action should propagate to the other airplane.

**__PLEASE ATTACH EVERYONE'S LOGS__**
[log.txt](https://github.com/Sequal32/yourcontrols/files/11359850/log.txt)
[log.txt](https://github.com/Sequal32/yourcontrols/files/11359854/log.txt)

**Discord**
Your discord name if you're in the YourControl discord server.

**Comment by rthom91** [comment]
Fixed in 2.7.7.
