### ISSUE TITLE
[BUG] Most controls non-functional with Asobo 747-8i and 787-10 after MSFS update.

### ISSUE THREAD

**Issue by DJRaov** [Sequal32/yourcontrols#213]
[BUG] Most controls non-functional with Asobo 747-8i and 787-10 after MSFS update.

**Describe the bug**
Most controls are non-functional after AAU2 update on the 787-10 and 747-8i with latest version of YourControls.

**To Reproduce**
1. Start as server.
2. Toggle switches/move throttle.

**Expected behavior**
Switches and other controls are expected to be synced between client and server.

**Comment by rthom91** [comment]
Both planes updated in 2.7.10.
