### ISSUE TITLE
A32NX MCDU and PFD [BUG]

### ISSUE THREAD

**Issue by MayDayNova** [Sequal32/yourcontrols#216]
When in shared cockpit, if one person inputs flightplan, init, perf etc, this is not visible to the other person. This makes the nav display and managed heading/altitude inoperative for the second person as well.

**Steps to Reproduce**
1. Start as server in A32NX
2. Begin inputting data in the MCDU

**Expected behavior**
Data would appear in both players' MCDUs and PFDs

**Comment by rthom91** [comment]
Programming the CDU should be done by one person and observed by the other. The FBW CDU is slower at entering key presses than other planes so this is probably just the result of not being on the same page when the programming started resulting in the visible de-sync. When de-sync like this occurs you can put yourself in observer mode and make corrections without affecting everyone else.
