### ISSUE TITLE
[Documentation] Include type of port forwarding in the readme

### ISSUE THREAD

**Issue by evilstiefel** [Sequal32/yourcontrols#22]
It'd be great if the readme could include the type of procotol used for port forwardings (TCP or UDP). This would make configuring firewalls and forwardings easier.

(Edit: that's not the label I wanted to assign, don't think I can change it)

**Comment by Sequal32** [comment]
Thanks! Added in 7ba0172db8835adabae52dfcd172bfae1dd5d869.
