### ISSUE TITLE
Use React for frontend UI

### ISSUE THREAD

**Issue by Sequal32** [Sequal32/yourcontrols#23]
Current code is very messy with all the state changes. Data doesn't update often, react would be a good fit. Perhaps a transition to [Tauri](https://github.com/tauri-apps/tauri) would benefit as well.

**Comment by srounce** [comment]
May I suggest https://github.com/yewstack/yew instead of React?

**Comment by Sequal32** [comment]
Ah that seems great! This will be a better solution for the frontend, thanks.
