### ISSUE TITLE
~75% FPS drop 737NG EFB

### ISSUE THREAD

**Issue by lazerwolf22** [Sequal32/yourcontrols#231]
When using the EFB app on the PMDG 737-8 the guest PC has a massive FPS drop of around 75%+ making it unusable. We tested this several consecutive times. I would start the EFB app and his FPS would immediately drop from 45 to somewhere around 12 or less. When I pressed the home button on the tablet closing the EFB app his FPS immediately returned to normal. We repeated several times with the same result. The FPS on my host machine went relatively unchanged.

**Comment by rthom91** [comment]
Should be fixed with 2.8.0.
