### ISSUE TITLE
[BUG] COM/NAV/Squwak not syncing

### ISSUE THREAD

**Issue by MoritzT** [Sequal32/yourcontrols#24]
**Describe the bug**
JonFly and I did another test with the new update and it overall went fine. Most values synced, but COM/NAV frequencies still don't sync. Neither through virtual cockpit or Spad.Next external controls. Squwak in the G1000 also did not sync. These systems are crucial to make a proper VATSIM pilot/copilot flight and I would really like to see them work.

Also when we passed controls while current pilot had AP engaged the plane started to spin out of control.

We flew a D40NG and selected the right config.

Video here http://www.twitch.tv/ndeavor/v/785039532?sr=a&t=0s

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.
2. Transfer control to client
3. Change standby frequencies for COM1 or NAV1 or change Squwak code.

**Expected behavior**
COM/NAV frequencies sync and change when transfer button is pressed.

**Additional context**
Might be that the wrong SimConnect variables/events are used.

**__PLEASE ATTACH EVERYONE'S LOGS__**
On mobile, will have to add them later, if needed

**Discord**
nDeavor

**Comment by Sequal32** [comment]
Thanks for the feedback! COM/NAV frequency not being synced addressed in version `2.2.0-beta.1`. Hopefully having a new release will let the G1000 sync again. Unfortunately, the trim is a simulator bug https://forums.flightsimulator.com/t/g1000-autopilot-bug-trims-to-100/296885/18.
