### ISSUE TITLE
[BUG] Different navigation databases lead to desync

### ISSUE THREAD

**Issue by MrMinimal** [Sequal32/yourcontrols#25]
(Amazing project, we have tried it today and are abolutely sold.)

**Describe the bug**
yourcontrols 2.2.0
MSFS 1.10.7

I flew the A32NX today as a client and we ran into desync issues along the flight.
Everything went perfectly up until the point where an approach was manually entered into the CDU by the server.
You select an approach from a list in the CDU. If the client's and server's lists are the same it works out.

My server used Navigraph though, which replaces/expands the navigation database.
So his "25L" approach was the "07R" approach for me in the CDU's list.

**To Reproduce**
1. Start as server (Navigraph user)
2. Connect a client (non-Navigraph user)
3. Let the server change the approach to something in his list
4. Observe that the list elements will be sorted differently between client & server
5. If the server selects one list entry, different approaches will be selected between server & client

**Expected behavior**
The list of approaches in the CDU should be the same between server & client.

**Additional context**
I don't know how to fix this properly but I wanted to use this issue to talk about it.
If you can't fix it, maybe mention that client and server should have the same navigation databases for a smooth experience.

**Discord**
@MrMinimal

**Comment by Sequal32** [comment]
Unfortunately the way the synchronization works right now is by replicating button presses. If the MCDUs are different in any ways, these kinds of issues will occur. I'll mention this in the documentation, and hopefully I can find a solution to get data synced and not rely on button presses. Thanks!
