### ISSUE TITLE
Boeing B247D is still functional and has a mod that improves/fixes it

### ISSUE THREAD

**Issue by zaelu** [Sequal32/yourcontrols#252]
Boeing B247D is still functional and has a mod that improves/fixes it and can be found here:

https://flightsim.to/file/61806/sound-fix-for-the-right-flywheel-in-the-b247d

Even with this "YourControls" can't work with it?

**Comment by rthom91** [comment]
A mod is only going to carry a dead product so far. Eventually the plane may stop working entirely with sim updates. Because of that, support was removed.
