### ISSUE TITLE
[BUG] TBM930 touchscreen controls have a mind of their own

### ISSUE THREAD

**Issue by m2ed** [Sequal32/yourcontrols#26]
**Describe the bug**
TBM930 touch screen controls spazz out

**To Reproduce**
1. Start as server.
2. Let client join
3. Turn on battery, alternator
4. Attempt to push some of the buttons on the touch screen controls

**Expected behavior**
Touch screen controls do random things instead of doing what you are trying. For example try hitting flightplan, then add origin.
The touch screen controls go into completely different menus.

**__PLEASE ATTACH EVERYONE'S LOGS__**
[client_log.txt](https://github.com/Sequal32/yourcontrols/files/5471497/client_log.txt)
[server_log.txt](https://github.com/Sequal32/yourcontrols/files/5471498/server_log.txt)

**Comment by Sequal32** [comment]
Thanks! Redownload the latest release, I forgot to include some files.
