### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by UA463** [Sequal32/yourcontrols#289]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.
2. Transfer control to client
3. Flip the navigation lights.

**Expected behavior**
A clear and concise description of what you expected to happen. For example: Navigation lights are synced between all clients.

**Additional context**

**__PLEASE ATTACH EVERYONE'S LOGS__**
`Log.txt` can be found in the directory of the .exe file`

**Discord**
Your discord name if you're in the YourControl discord server.

**Comment by UA463** [comment]
Hello
Construction. PC-Alt(FS 2020) is connected to PC-Neu(FS 2020) Direkt via the Fritzbox   .
Both FS programs have started. Cessna 172SP. Same place, gate,........
I have the following problem:
From PC New (Host) I can control/operate the plane on PC-Alt (Join) simultaneously with the control of the plane! The same applies if PC-New is the HOST and PC-Alt is the JOIN. So far it works as it should!
However, if I want to control the plane from PC old (FS2022) to PC new (FS 2024), it doesn't work!  However, the control/setting of the HDG, ALT,....!  Only the control elevator, rudder, ailerons, throttle does not work!
What kind of error is there?
Thanks for the effort
m.f.Gr.
Uwe22

**Comment by UA463** [comment]
Hello
Construction. PC-Alt(FS 2020) is connected to PC-Neu(FS 2020) Direkt via the Fritzbox   .
Both FS programs have started. Cessna 172SP. Same place, gate,........
I have the following problem:
From PC New (Host) I can control/operate the plane on PC-Alt (Join) simultaneously with the control of the plane! The same applies if PC-New is the HOST and PC-Alt is the JOIN. So far it works as it should!
However, if I want to control the plane from PC old (FS2022) to PC new (FS 2024), it doesn't work!  However, the control/setting of the HDG, ALT,....!  Only the control elevator, rudder, ailerons, throttle does not work!
What kind of error is there?
Thanks for the effort
m.f.Gr.
Uwe22
Mail: dumas.v@gmx.de

**Comment by rthom91** [comment]
Where does it say the application is compatible with 2024.
