### ISSUE TITLE
[SUGGESTION] Force getting control

### ISSUE THREAD

**Issue by marccreal** [Sequal32/yourcontrols#31]
I would suggest that it should be possible for the person not in control to force getting control (as an optional feature that can be activated by the server). If you fly in kind of an "instructor and student" configuration, this would add more realism and immersion.

**Comment by MrMinimal** [comment]
I wondered if this could be done automatically if enough input is given from the party which isn't in control.

**Comment by Sequal32** [comment]
Added in a6cf423e6499152b06f317695173250b63139acd, will close when new release is out.

**Comment by Sequal32** [comment]
2.4.0 is now out.
