### ISSUE TITLE
Suport Working Title G1000/G3000

### ISSUE THREAD

**Issue by SkyCmmd** [Sequal32/yourcontrols#34]
**Describe the bug**
when you install yourcontrols - it reverts touchscreen displays back to default. even if both users use working-title g300 mod

**To Reproduce**
1. install working title g3000 mod
2. enjoy the expanded options and realism of the touchscreens.
3. install yourcontrols (drop the right folder into community)
4. deploy sad face when you realized the touchscreens been reverted back

just wanted to call it out - hopefully the two mods can co-exist!

**Comment by Sequal32** [comment]
Release 2.5.0 should address this issue.
