### ISSUE TITLE
Low Framerate

### ISSUE THREAD

**Issue by MatiasBordoy** [Sequal32/yourcontrols#35]
hi amazing work!
But when using this  addon, i'm experiencing a considerable framerate loss.
I have tried with cessna 172 and airbus a320 flybyware with shared cokpit.

What can be the problem?

**Comment by Sequal32** [comment]
Hmm I haven't had anyone report frame loss... Does this happen when you're in control or monitoring, or just all the time?

**Comment by MatiasBordoy** [comment]
I´m going to test it tomorrow again in a long flight. It happened all the time.
Keep this issue open so i can tell you more details.

**Comment by Sequal32** [comment]
Make sure to download the newest release, hopefully that contributes to fixing the FPS issue.
