### ISSUE TITLE
[BUG] Incompatibility with DA62x Mod

### ISSUE THREAD

**Issue by marccreal** [Sequal32/yourcontrols#37]
There is a conflict between YourControls and the DA62X-mod. With incompatibililty, I mean just having the YourControl-folder in the Community-folder (without having a shared cockpit session active) and trying to use the DA62X. Then the alternators fail and the the load only going up to ~70% at full throttle (there might be more that I have not realized yet).

I had a look at the folder structure of the two mods, I guess the problem arises from (one of) these two conflicting files:
![image](https://user-images.githubusercontent.com/63705372/98932744-05972d80-24e0-11eb-8d87-2e2d19f43322.png)

As a next step, I also compared to the default DA62 in the “Official” folder. The difference of the PANEL.CFG is very easy to visualize (left: DA62X, middle: YourControl, right: default:
![image](https://user-images.githubusercontent.com/63705372/98932789-16e03a00-24e0-11eb-96d8-7f1044f72c27.png)
So here the analysis is straightforward: the two mods define different “Vcockpit05” objects.

The difference in the DA62_INTERIOR.xml is a bit more messy, In the DA62X version, of course there is some stuff added compared to the default version. But the YourControl-Version only differs marginally from the default one - and strangely: Different XML-Tags <ModelBehaviors> vs. <Behaviors>, different variable name L vs I... I’m beginning to suspect that the YourControl-File is just an older version of the default?

**Comment by Sequal32** [comment]
Thanks for this! Seems like there are a bunch of mods that build upon the base aircraft so I’ll need to make every aircraft that YourControls modifies an optional part to install. I’ll also look into supporting aircraft like these.

**Comment by mrtommymxr** [comment]
@Sequal32 perhaps we can get "YourControls" working with the DA62X. 
Hit me up on discord MrTommymxr#0069

**Comment by rthom91** [comment]
Please provide a list of everything that doesn't work on the DA-62X when running the stock DA-62 profile.

**Comment by rthom91** [comment]
Beta compatibility released in 2.5 beta. WT G1000 support not added yet.

**Comment by Sequal32** [comment]
Release 2.5.0 should address this issue. The installer has an optional feature now to install compatibility for the stock DA62.
