### ISSUE TITLE
[BUG] XCub not syncing aircraft position

### ISSUE THREAD

**Issue by MrMinimal** [Sequal32/yourcontrols#42]
**Describe the bug**
Buttons and levers sync, client stays on same position.
Starting with pushback I could tell no sync was happening.

**Additional context**
v2.3.1

**__PLEASE ATTACH EVERYONE'S LOGS__**
[log_server.txt](https://github.com/Sequal32/yourcontrols/files/5542771/log.txt)

[log_client.txt](https://github.com/Sequal32/yourcontrols/files/5542767/log_client.txt)

**Discord**
MrMinimal

**Comment by Sequal32** [comment]
Ooops very simple fix - add this to the include at the top of the definition file: 
`- definitions/modules/physics.yaml`
looks like the pitts doesn't have that either...

**Comment by Sequal32** [comment]
Fixed in b322dac753819d96975986f06237f8eff768c359, will close when new release is out.
