### ISSUE TITLE
Auto Pilot 

### ISSUE THREAD

**Issue by SkallR** [Sequal32/yourcontrols#43]
When we engage the AP, the trim of the non-flying pilot is going full up with a lot of noise, impossible to move. It become then impossible to transfer controls because the plane would have weird behavior.

**To reproduce**
Take off and engage AP

**Comment by Sequal32** [comment]
Unfortunately the trim bug is an issue with active pause (which this program utilizes). I do have a solution in mind in order to avoid using active pause and making position updates even smoother so I'll keep this open till then.

**Comment by Sequal32** [comment]
Release 2.5.0 should address this issue.
