### ISSUE TITLE
[BUG] Model Matching in VATSIM

### ISSUE THREAD

**Issue by OG1042** [Sequal32/yourcontrols#44]
The Bug: When we are flying in VATSIM the model matching is working on our plane, Which means I can see our plane 2 times on each other and we cant use the shared cockpit at all in VATSIM. (one connected as pilot one connected observer and still see the plane 2 times).  

The reproduce:
1. Connecting to VATSIM
2. Model Matching Works
3. 2 Planes Over Each Other and blocking their view for the cockpit.

**Comment by TwitchyShell** [comment]
What callsign did both of you connect as?

**Comment by OG1042** [comment]
> What callsign did both of you connect as?

we used like for example the pilot: SAS229 and the observer: SAS2291

**Comment by TwitchyShell** [comment]
Attempt connecting master as SAS229 and slave as SAS229A

**Comment by OG1042** [comment]
> Attempt connecting master as SAS229 and slave as SAS229A

will try! if it won't work should I write here?

**Comment by TwitchyShell** [comment]
Keep us posted so we can keep this ticket open or close it.

Please also verify again that slave (the one with the letter suffix at the end) connects as observer onto VATSIM (checkbox on the bottom on the connection menu)

![image](https://user-images.githubusercontent.com/74171501/99788786-89bd6680-2b19-11eb-8099-2a99b374d83e.png)

**Comment by OG1042** [comment]
2 of us should be in observer mode? or just the pilot?

**Comment by Amit0950** [comment]
Please have the pilot connect as the normal callsign, and the Co-Pilot add an A to the end of the callsign and connect as an observer
Pilot=DLH2106 Not ticked as an observer

Co Pilot=DLH2106A (connect as an observer) ticked

Third Officer=DLH2106B (connect as an observer) ticked

and that continues.....

**Comment by Amit0950** [comment]
Please have the pilot connect as the normal callsign, and the Co-Pilot add an A to the end of the callsign and connect as an observer
Pilot=DLH2106 Not ticked as an observer

Co Pilot=DLH2106A (connect as an observer) ticked

Third Officer=DLH2106B (connect as an observer) ticked

and that continues.....

**Comment by OG1042** [comment]
Understood. thank you!

**Comment by Amit0950** [comment]
Yep no problem have fun!
