### ISSUE TITLE
[BUG] FMC Button presses not syncing

### ISSUE THREAD

**Issue by ryanj3699** [Sequal32/yourcontrols#45]
**Describe the bug**
We have had trouble with the FMC on all the planes we have flown so far (A32nx, TBM, DA62). When I am in control and am trying to program the FMC, my friend is not seeing any of the buttons being pressed on the fmc. I program the flight plan and his FMC remains on the initial page when the battery/app start. Due to his FMC not registering my inputs, he cannot see any part of the flight plan. 

**To Reproduce**
1. Start as server.
2. Transfer control to client
3. Start battery/apu.
4. Try programming FMC

**Expected behavior**
The FMC will sync button presses between the clients so that my friend will actively see my programming of the FMC and the flight plan that is created.

**Comment by Sequal32** [comment]
Hi, if you have discord feel free to come to the server listed in the readme in the homepage of this repository so we can discuss this in real time.

Did all the other switches sync? If not, this is commonly caused by an installation issue of the community package.

**Comment by ryanj3699** [comment]
Okay I will join the discord tonight. All the normal buttons sync together and work other than internal lighting (such as flood lights and PFD lighting), but I'm not sure if that is supported.

**Comment by ryanj3699** [comment]
Hello, I just got it to work. I had to uninstall, then reinstall the files to get it to work. Thank you for such a great mod!

**Comment by Sequal32** [comment]
Glad to hear it! Enjoy it!
