### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by RushGall** [Sequal32/yourcontrols#47]
Need a tutorial video on Youtube!!! Please!!! My English is poor. The translation is literal and incomprehensible. Thanks!

**Comment by Amit0950** [comment]
There is a tutorial in discord

**Comment by SafeShows** [comment]
https://www.youtube.com/playlist?list=PLFq22qaNfufDauiMMNmsoTA_tx7YHp-Q-

**Comment by Amit0950** [comment]
Was just gonna do that, that should help you

**Comment by RushGall** [comment]
Thanks a lot, but I've already seen it! Need the moment of connection in MSFS 2020!

**Comment by Amit0950** [comment]
https://www.youtube.com/watch?v=W2bw_Ui5nzw&list=PLFq22qaNfufDauiMMNmsoTA_tx7YHp-Q-&index=2 thats the video that should help

**Comment by RushGall** [comment]
thank you, I saw it too. what the co-pilot should do when entering the simulator. How do I choose my partner's plane?

**Comment by Amit0950** [comment]
"Active aircraft" connect when in ramp or parking, and then connect or start

**Comment by RushGall** [comment]
Should the server be online or offline?

**Comment by Amit0950** [comment]
Online

**Comment by RushGall** [comment]
OK! Thank you very much! I will try!!!
