### ISSUE TITLE
[BUG] Blank white window when opening sharedcockpit.exe

### ISSUE THREAD

**Issue by PuL9** [Sequal32/yourcontrols#48]
**Describe the bug**
No UI is showing up and the software crashes when trying to resize the window

**To Reproduce**
1. Launch sharedcockpit.exe

**Expected behavior**
UI should show up

**Additional context**
I have followed all tutorials.
v1.3.0 works fine
https://i.imgur.com/vzmox81.png

**__PLEASE ATTACH EVERYONE'S LOGS__**
07:39:07 [INFO] Creating webview...
07:39:07 [INFO] Spawning webview thread...

**Comment by SafeShows** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #48: [BUG] Blank white window when opening sharedcockpit.exe](https://trello.com/c/D3zvlNHL/1-issue-48-bug-blank-white-window-when-opening-sharedcockpitexe)

**Comment by Sequal32** [comment]
Fixed in 104a32a3c63c253d14d3f30fb07bafb216272341. For some reason some computers crash on loading the webview with Edge as the backend for the UI. Will close on the next release.

**Comment by Sequal32** [comment]
Release 2.3.3 now includes a fix for this!
