### ISSUE TITLE
[SUGGESTION] Move WASM module for better compatibility

### ISSUE THREAD

**Issue by qwrtty** [Sequal32/yourcontrols#49]
It would be nice if you could move YourControlGauge.wasm to the new standalone modules folder.

From the [development update on November 12th](https://www.flightsimulator.com/november-12th-2020-development-update/):
>- We added support for standalone WASM modules. These should be placed in a “modules” folder located at the root of the package, and will be loaded automatically when the said package is mounted. The “module_init” and “module_deinit” functions will be called upon loading/unloading.

Some advantages this could bring:
- Easier to support new aircraft (no more aircraft-specific panel.cfg)
- Better compatibility with mods (would fix part of #37) and other WASM-dependent stuff (such as RealSimGear's software or a future version of SPAD.Next)
- Ability to support (Premium) Deluxe or other payware aircraft (without editing the official package's layout.json)
- Potentially less breakage on MSFS updates due to no panel.cfg editing

Though I have no clue how well the new standalone WASM API works or how much work it would be to port YourControlGauge.wasm to it.

Off-Topic: thank you for making this! I'm considering using YourControls to make non-SimConnect accessible parts of the cockpit ([e.g. Garmin map zoom](https://forums.flightsimulator.com/t/simconnect-and-gps-event-ids/308990)) accessible to home cockpit builders. It's really nice to have the WASM part of this already solved.

**Comment by Sequal32** [comment]
I would love love to do this, but it seems like calling any function from the gauge api from a standalone module locks it up, as it probably needs to be injected into the panel of an aircraft to actually access it. This would honestly solve so many problems and I hate that it conflicts with other mods so much.

**Comment by qwrtty** [comment]
Ah damn. I asked the guy who makes SPAD.next on Discord, who is working on a Wasm module for LVAR support. Apparently he has encountered the same issue and it seems like he hasn't found a solution yet. Thanks for giving it a try though!

![image](https://user-images.githubusercontent.com/14903710/100551097-94dd6880-3276-11eb-9b0d-25bea7d335ca.png)

**Comment by Sequal32** [comment]
I looked into this again, it seems to work now... not sure if something changed or I did something wrong when I was testing it the first time but I will move to a standalone module now :D

**Comment by mishal321** [comment]
Auto pilot screws up for the person I give control to, his solo flights are working. it's just when we connect with your controls.

**Comment by Sequal32** [comment]
Incorporated into 2.4.0!
