### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by txCarlos** [Sequal32/yourcontrols#51]
When I am in mid-flight, in MSFS2020, my friend begins to slow down or starts to deviate from the route while I am still fine, when I try to reconnect I appear at 300 knots or more, he cannot go down because he is going up and I trying to go down This happens when one of the two is in command, and it is quite annoying because if we are in IVAO or Vatsim we have to end the flight because either he gets out of sync or I get out of sync, please fix this as soon as possible, this error came with him FBW 32NX mod Autopilot patch, please fix it

**Comment by txCarlos** [comment]
@Sequal32 Please view this, isnt possible to fly with YourControls :(

**Comment by SafeShows** [comment]
What version of YourControls are you using?

**Comment by txCarlos** [comment]
V2.3.1

**Comment by Sequal32** [comment]
Will be looking to fix this in the next stable, thanks.

**Comment by C0PAN** [comment]
i'm experiencing a similar issue flying TBM, after take off the desync starts and the aircraft crashes to whom is on "slave" mode.

**Comment by Sequal32** [comment]
Try the new release, open a new issue if this still persists.
