### ISSUE TITLE
[BUG] NDB frequency tuning on G1000 has an off-by-one error

### ISSUE THREAD

**Issue by hrafnkelle** [Sequal32/yourcontrols#52]
**Describe the bug**
When tuning the NDB/ADF receiver in g1000 (e.g. C172 skyhawk) in a shared session the decimals are off by one between the two users, server and client. E.g. when tuning 0355 kHz and adjusting the last digit (5), one will show 5 while the other will show 4.

**To Reproduce**
1. Two users spawn in on a common location, one starts server, other client and connects
2. Start the plane (suggest C172 with G1000)
3. Go to the ADF/DME on the G1000 and tune the frequency

**Expected behavior**
Both systems should show same frequency on NDB receiver, but they are off by one on the digit being tuned.

**Comment by Sequal32** [comment]
Will look into it, thanks!

**Comment by Sequal32** [comment]
Fixed in 2.4.0.
