### ISSUE TITLE
REQUEST: Clone and/or Build Instructions

### ISSUE THREAD

**Issue by ElSrJuez** [Sequal32/yourcontrols#53]
Hi, I have been studying the code for a while, could you provide some guidance on requirements and dependencies for cloning, or build details?
Thanks!

**Comment by SafeShows** [comment]
The front end / UI is in the web folder and the dependencies are in the cargo.toml file

Why are you going to do/modify?

**Comment by Sequal32** [comment]
Hoping to write up a `Contributing.md`, but haven't gotten around to it yet. Sorry for the wait.

**Comment by ElSrJuez** [comment]
> The front end / UI is in the web folder and the dependencies are in the cargo.toml file
> Why are you going to do/modify?
Nothing yet, for now just trying to understand; I tried to build it and didn't get too far beyond cloning it : )

**Comment by Sequal32** [comment]
Added in 7e7b317f084df85ff57d6376b70bee48631f29da
