### ISSUE TITLE
[BUG] Shared Cockit not running...

### ISSUE THREAD

**Issue by adonix-dev** [Sequal32/yourcontrols#54]
**Describe the bug**
sharedcockpit.exe runs but kill after 2 seconds on Windows 10.

**Log File**
22:31:33 [INFO] Creating webview...
22:31:33 [INFO] Spawning webview thread...

**Folder**
![image](https://user-images.githubusercontent.com/31833518/101295096-c11b5b00-381b-11eb-92e1-1606db41657e.png)

**Comment by Sequal32** [comment]
Similar to #48 - there's a beta version you can use if you join the discord which fixes this issue

**Comment by adonix-dev** [comment]
You were right as if it was you that coded the app lol !
Thanks ;)
A.

**Comment by Sequal32** [comment]
Release 2.3.3 now includes a fix for this!
