### ISSUE TITLE
[BUG] A320 black screens

### ISSUE THREAD

**Issue by LFSS** [Sequal32/yourcontrols#57]
**Describe the bug**
All of the A32NXscreens spawn in blacked out. I've got the newest version of YourControls (2.3.2)

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Install YourControls
2. Choose the A32NX
3. Spawn

**Expected behavior**
The screens were supposed to be on

**Comment by SafeShows** [comment]
This mod doesn’t work with the stock A320
It only works with the FBW A320 one
Here is there download page https://flybywiresim.com/a32nx

**Comment by LFSS** [comment]
> This mod doesn’t work with the stock A320
> It only works with the FBW A320 one
> Here is there download page https://flybywiresim.com/a32nx

I edited my original post because I got it mixed up: I tried with the A32NX with liveries, with no liveries, reinstalling YourControls, reinstalling A32NX, but still, black screens all around

**Comment by Sequal32** [comment]
If you're using the A32NX stable, try using the A32NX dev version instead.

**Comment by Sequal32** [comment]
New release published that might address this issue. Comment if this still persists.

**Comment by Khitiara** [comment]
not OP but just got this issue on latest yourcontrols and latest a32nx dev
