### ISSUE TITLE
[BUG] AP not working correcly between client and server (TBM930)

### ISSUE THREAD

**Issue by DenisFerrari74** [Sequal32/yourcontrols#60]
YourControls version 2.4.0.0 (did not have before)

Tried to fly with a friend with TBM 930, same exact starting place and parking, same time, mutliplayer off.

All seemed fine until we started to use the AP.

From the very beginning, as soon as client inserted proper NAV and COM freq's in the PFD, I could see them correclty, but as soon as he confirmed on my PFD different freq's started to appear. And of course, on my MFD no correspondent data indicated. While on his one all was appearing correct.

Then, I tried to move VS setting, on mine was fine, on his one 0. And it seemed his value jumped up as soon as he touched the same VS button on his cockpit view.

Once in flight, I asked him (client) to engage autopilot and things started to go wrong too. It seems that unique way to let us use the AP was both of us doing the same exact operations on AP buttons and settings. 

Very strange indeed.

The rest seem working very well instead, so shared controls (when control given/taken), flaps, main gear, lights buttons, top cockpit buttons, engine starting procedures and more.

Maybe we did something not correct in the very beginning once both on board and just after I clicked on his name "taking him in", so not anymore an Observer?

Thank you!

**To Reproduce**
1. Start as server.
2. Accept a client
3. Play with AP and ask client to operate on the AP and NAV/COM radios settings, checking thh PFD and MFD indications

Here's our logs:
[log_client.txt](https://github.com/Sequal32/yourcontrols/files/5775384/log_client.txt)
[log_server.txt](https://github.com/Sequal32/yourcontrols/files/5775386/log_server.txt)

**Discord**
Tomcat74

**Comment by Sequal32** [comment]
The new stable (2.4.1) that is out should address this.

**Comment by DenisFerrari74** [comment]
Wow, that's an excellent news!! Can't wait to test it during next days! Thank you and congratulations for the great job! Keep on developing, this is no doubts one of the best mod FS2020 could have!!
