### ISSUE TITLE
[BUG] Aircraft position being off causes causes various problems

### ISSUE THREAD

**Issue by foxmike80** [Sequal32/yourcontrols#61]
First of all, thanks for your great work! A friend and I have been enjoying YourControl in some magnificent flights using FBW’s A32NX. However, we came across some issues and one possible cause that we wanted to share:

**Describe the bug**
1.	Pilot B’s FD is always a bit off although the plane is perfectly aligned with the route. We tested handing over controls with A/P engaged and disengaged and concluded that this is causes by a difference in position of our two aircraft. When Pilot A was in control, his FP was perfectly centered, and Pilot B’s FD was commanding a left turn. When we swapped controls, the aircraft started a left turn to follow B’s FD and Pilot A’s FD now directed to the right. Our conclusion was that, once controls are swapped, the aircraft of the now pilot flying is trying to get to the position of the former pilot flying and vice versa. This might be caused by both aircraft being a few (hundred?) meters off.
2.	Also related, our MCDU was getting out of sync shortly after departure when Pilot A entered a direct. “His” aircraft had already passed WP 1 and was inbound WP 2 when he entered a direct to WP 3. Pilot B’s aircraft, being a few meters behind, had not yet passed WP 1 and pilot A’s direct WP 3 became a direct WP 2 for pilot B because that was the next line in his MCDU. From now on, our MCDU flightplans were off by one waypoint. 
We could workaround that issue by using the scratchpad to manually enter a direct to WP 4 (typing, not using the LSK!), now both MCDUs deleted all waypoint before WP 4 and we were synced again.

**To Reproduce**
Steps to reproduce the behavior, for example: 

**Expected behavior**
Is, is there a way to better sync the aircraft’s position? 
Is it possible to implement a way to manually sync the content of the MCDU or even the status of the aircraft – perhaps with a “force sync” button in the YourControl software - using variables and not keypresses.

**Additional context**
Again, I wanted to emphasize how impressed by your work we are and how grateful to finally being able to share a plane, your work is much appreciated!

**__PLEASE ATTACH EVERYONE'S LOGS__**
`Log.txt` can be found in the directory of the .exe file`

**Discord**
Your discord name if you're in the YourControl discord server.

**Comment by Sequal32** [comment]
I believe this is an issue with utilizing Active Pause. 2.5.0 will fix this soon.

**Comment by foxmike80** [comment]
Hi, thanks for your reply. I don't think it was caused by active Pause. We were online on vatsim and both never used it. Looking forward to 2.5, though. Thanks for all you efforts and great work.

**Comment by Sequal32** [comment]
Sorry should've been more specific - this mod utilizes Active Pause to freeze the aircraft in order to sync positions. I'm looking to implement position syncing differently in 2.5.0. Thanks!

**Comment by foxmike80** [comment]
Now that is great news. Really looking forward to it. Keep up the great work!

**Comment by Sequal32** [comment]
Release 2.5.0 should address this issue.
