### ISSUE TITLE
[BUG] Server stops sending events to client, but can continue to receive from client

### ISSUE THREAD

**Issue by JeremyWau** [Sequal32/yourcontrols#64]
**Describe the bug**
Client does not receive events from the server anymore, but server keeps receiving them.
Checking the logs, there is nothing sent by the server to the client (easy to see as there is a "[WARN] Could not deserialize packet! Reason: wrong msgpack marker FixPos(65)" log line for each event sent).
But after some packets received from the client, the server suddenly sends all the packets that were probably cached.
After that the planes are again synced until that behaviour comes again.

**To Reproduce**
1. Open MSFS with an airplane (tried A32NX - flybywire - and DA62 - default msfs airplane)
2. Start as server. (using direct ip, but seems to happen with the other methods too)
2. Client connect to the server
3. Trigger any events in the cockpit (radio freq change, CDU buttons, ...) until the client stops receiving the data.

**Expected behavior**
Packets on the server application should be sent directly to the client and not after some delay after receiving data from the client multiple times.

**Additional context**
I don't know what triggers that state exactly, it seems to have happened with and without Ivao Core and Pilot UI running, but just adding it in case that may be relevant.
As it happens with the default DA62, I guess this is really network related. We made a serie of pings and only a few there and there ended as timeouts, other than that all the others are < 30ms.

**__PLEASE ATTACH EVERYONE'S LOGS__**
I just replaced ip by x.x.x.x:{port}
[log-bug-server.txt](https://github.com/Sequal32/yourcontrols/files/5824614/log-bug-server.txt)
[log-bug-client.txt](https://github.com/Sequal32/yourcontrols/files/5824615/log-bug-client.txt)

**Discord**
Will provide it upon request.

**Comment by Sequal32** [comment]
I implemented a fix for this in adda4aad5bf9b9452a650e58bfcbbb050e38f591. Apparently the UDP library I’m using only resends dropped packets upon receiving a “reliable” packet with an acknowledgement header. The default heartbeat implementation doesn’t send reliable packets so it simply keeps the connection alive. Thanks for looking into this!

**Comment by JeremyWau** [comment]
Hey,
Thanks a lot for the reply and the work there, really a nice work you did !

This definitely fits the description of what we experienced and tried to chase down. Looking forward the beta/stable including that commit :)

**Comment by Sequal32** [comment]
New stable 2.4.1 is out that addresses this!

**Comment by JeremyWau** [comment]
Hey, just to come back to you about this, we did a one hour flight without any sync issue at all on the A32NX, thanks ! :)
Before landing, the client experienced a disconnection but that may be related to the timeout setting (currently 5).

Again thanks a lot for the work there, wish you a nice day !
