### ISSUE TITLE
[BUG] Bad Desync

### ISSUE THREAD

**Issue by americanhawk1** [Sequal32/yourcontrols#67]
On the 152, all syncing works fine, until I start up the aircraft and then turn it back off. On the co-pilots screen, nothing turns off and everything screws up after that.

Honestly, after awhile (after heeding all of your instructions), everything breaks after awhile. Some things I can see still syncing, but some things you can. 99% of the time, my co-pilot can't even see my aircraft move.

- Just tried another aircraft. I honestly don't know how people even get this to work. NOTHING, is working 100% accurately.

**Comment by Sequal32** [comment]
Please attach you and your copilot's logs, otherwise I have no clue what the problem is nor how to resolve it. You can find it in the same folder as the .exe file. You may wish to remove the IP addresses in the log.txt file.

**Comment by americanhawk1** [comment]
[PILOT(CLIENT).txt](https://github.com/Sequal32/yourcontrols/files/5884408/PILOT.CLIENT.txt)
[CO-PILOT(HOST).txt](https://github.com/Sequal32/yourcontrols/files/5884409/CO-PILOT.HOST.txt)

We were using Hamachi because port-forwarding wasn't working.

**Comment by Sequal32** [comment]
It's possible that using Hamachi could've been the cause, as for a free service, their servers aren't the best. If you've already tried port forwarding and Cloud Server there's not much else you can do at this point. I'm currently working on another method for connecting which will streamline the process and allow everybody with different network settings to be able to connect.

**Comment by americanhawk1** [comment]
Alright. The only reason I didn't think it would be Hamachi was because the process is so repeatable after trying many times. How could it drop the same packet over and over?

**Comment by Sequal32** [comment]
The new release 2.5.0 should address this issue.
