### ISSUE TITLE
G3000 in TBM FPS Problem

### ISSUE THREAD

**Issue by flodwo** [Sequal32/yourcontrols#68]
Hello!

In this new and actual G3000 Mod, I loose significantly my FPS after about 1 hour of flight time!
In the last mod, i didn't have this problem. I have about 50 FPS and after a while it drops to 33 FPS.

Thats not a normal behaviour. In the external view, I get abot 65 FPS.

Please help

**Comment by Sequal32** [comment]
Hi! When you refer to this "new and actual G3000 Mod" what do you mean by that? Have you confirmed that if you uninstall YourControls, this issue goes away?

**Comment by flodwo** [comment]
I will check that with the older mod and report it!
