### ISSUE TITLE
[BUG] Tablet does not sync in the a32nx

### ISSUE THREAD

**Issue by Samueleonard** [Sequal32/yourcontrols#69]
**Describe the bug**
Tablet does not sync between clients in the a32nx

**To Reproduce**
1. Start as server.
2. turn on the tablet
3. observe that the tablet does not sync for the other person
4. repeat with other person, tablet never syncs

**Expected behaviour**
tablet clicks are synced between clients, as every other button does already

**Additional context**
i assume this is just because it has been coded, not really a bug per se
similar issue with the FPV button on the FCU

**Discord**
1samueleonard1#0001

**Comment by Sequal32** [comment]
While waiting for a new stable, you can try out the beta that you can find [here](https://github.com/Sequal32/yourcontrols/commit/a9edfac0aa92ca31921c993b11e6721808571290).

**Comment by Sequal32** [comment]
The new release 2.5.0 should address this issue.
