### ISSUE TITLE
[BUG] Starter button not holding for the observer in the DR400-100.

### ISSUE THREAD

**Issue by CptAdhoc** [Sequal32/yourcontrols#70]
**Describe the bug**
In the DR400-100, the starter button is just pressed for the observer when the person in control hold it.  In consequence, the engine is not starting for the observer.

**To Reproduce**
1. Go in a DR400-100 with your best friend or a nice pilot.
2. As pilot, hold the starter button for 10 seconds, engine start.
3. As observer, observe that the starter button is just pressed for 1 second, observer engine not starting.

**Expected behavior**
Starter button must be hold in the observer side as long as the pilot hold it.
Engine must start for both pilot and observer.

**Comment by Sequal32** [comment]
The new release 2.5.0 should address this issue.
