### ISSUE TITLE
[BUG] AP not correctly syncing for both sides

### ISSUE THREAD

**Issue by stefanone72** [Sequal32/yourcontrols#71]
**Describe the bug**
AP: Co-pilot can move the switches but not affect really the behaviour of the plane. For example, If my co-pilot set FL100, I can see the correct number but wan't be really so, If I touch the switch, the altitude return to be my last altitude setted.
Same for the speed.

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.
2. Transfer control to client
3. Try to set up the AP togheter and check if this affect the fly.

**Expected behavior**
AB fully functions sync between pilots.

**Additional context**

**__PLEASE ATTACH EVERYONE'S LOGS__**
`Log.txt` can be found in the directory of the .exe file`

**Discord**
Your discord name if you're in the YourControl discord server.

**Comment by Sequal32** [comment]
Autopilot definitions were overhauled in https://github.com/Sequal32/yourcontrols/commit/a9edfac0aa92ca31921c993b11e6721808571290 which should address this issue.
While waiting for a new stable, you can try out the beta that you can find [here](https://github.com/Sequal32/yourcontrolsinstaller/releases/download/1.2.1/installer.zip).

**Comment by stefanone72** [comment]
Thank you so much

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Connor T<mailto:notifications@github.com>
Inviato: domenica 14 febbraio 2021 21:19
A: Sequal32/yourcontrols<mailto:yourcontrols@noreply.github.com>
Cc: stefanone72<mailto:stefano.valle@hotmail.com>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [Sequal32/yourcontrols] [BUG] (#71)


Autopilot definitions were overhauled in a9edfac<https://github.com/Sequal32/yourcontrols/commit/a9edfac0aa92ca31921c993b11e6721808571290> which should address this issue.
While waiting for a new stable, you can try out the beta that you can find here<https://github.com/Sequal32/yourcontrolsinstaller/releases/download/1.2.1/installer.zip>.

**Comment by Sequal32** [comment]
The new release 2.5.0 should address this issue.
