### ISSUE TITLE
[BUG] New Radio Panel A32NX not synching properly

### ISSUE THREAD

**Issue by foxmike80** [Sequal32/yourcontrols#72]
**Describe the bug**
Probably caused by the accelerated knobs, causes Radio Coms to coming out if sync. 

**To Reproduce**

1. Start session with latest A32NX mod (build 2021-02-05T16:30:56+00:00)
2. Connect using YourControls
3. F/O changes frequency by turning the knob quickly
4. Observe that both planes show different frequencies

**Expected behavior**
Frequencies should be identical - perhaps synchronising actual COM frequencies via simconnect  rather than synchronising click or mousewheel events.

**__PLEASE ATTACH EVERYONE'S LOGS__**
[log.txt](https://github.com/Sequal32/yourcontrols/files/5936524/log.txt)
[log-client.txt](https://github.com/Sequal32/yourcontrols/files/5936525/log-client.txt)

**Discord**
Your discord name if you're in the YourControl discord server.

**Comment by Sequal32** [comment]
Thanks! This is added in https://github.com/Sequal32/yourcontrols/commit/a9edfac0aa92ca31921c993b11e6721808571290.
You can try the beta [here](https://github.com/Sequal32/yourcontrolsinstaller/releases/download/1.2.1/installer.zip) while waiting for a new stable.

**Comment by foxmike80** [comment]
We just tested in the new beta 2.5.0. The problem is much better, but still there. When we quickly changed com frequencies using the mouse wheel, the frequencies were off in some cases.

**Comment by foxmike80** [comment]
We did some more testing. Often inputs seem to be sent twice. One click on the frequency knob causes two steps in frequency change. This does not happen when not connected to YourControls.

This seems also to happen when pressing the ACT/STBY switch. The frequencies change quickly as intended but immediately change back. This is obviously to quick for the sync process because sometimes this change is reflected on the partner plane and sometimes it isn't causing chaos.

**Comment by Sequal32** [comment]
New beta out that addresses this issue. You can get it from the same installer.

**Comment by foxmike80** [comment]
Just checked the new beta and we are almost there 👍.
Syncing now works flawlessly - great job! Only thing that we noticed today is that the last digit of the radios do not sync properly.
If one pilot changes the frequencies from 120.000 - to 120.00**5** and 120.010 YourControls seems not to sync the middle step. On the other pilots side he sees 120.000 - 120.00**0** and then 120.010. This only happens for some frequencies when the last digit is a 5. Can by reproduced 100% using the frequencies mentioned above.

**Comment by Sequal32** [comment]
Thanks for the feedback! I’ve implemented a fix in https://github.com/Sequal32/yourcontrols/commit/96a75476d79105e9eddf8b0385166db167d52f3a which is implemented in 2.5.0-beta.3 which you can get again via the above installer.

**Comment by foxmike80** [comment]
Wow, great job. Radios now sync perfectly! No more issues on this end.
