### ISSUE TITLE
[BUG] Constant disconnect between EU and Canada

### ISSUE THREAD

**Issue by August78** [Sequal32/yourcontrols#73]
**Describe the bug**
When doing shared cockpit in the a320 fbw with my friend from Canada, we get constant disconnects. This doesnt happen when flying with friends in eu. It happens maybe once every 5-10 minutes or so.

**To Reproduce**
Use cloud server, where he is the host (canada), or where I am (eu). After 5-10 minutes, either his client disconnects, and dissapears, or at least kicks me out. 

**Expected behavior**
Stabile connection.

**Additional context**
We are both on wired internet with good speed. 

**__PLEASE ATTACH EVERYONE'S LOGS__**
**__REDACTED__**

**Discord**
Your discord name if you're in the YourControl discord server.
We are not on your discord server

**Comment by August78** [comment]
We were wondering if perhaps there is some sort of latency threshold that the application permits, and that cross contintent shared cockpit perhaps needs less restrictive threshold to allow for normal operation without disconnects?

**Comment by Sequal32** [comment]
Hi! You can try increasing the `Connection Timeout` in the settings in the new beta that you can find [here](https://github.com/Sequal32/yourcontrols/commit/a9edfac0aa92ca31921c993b11e6721808571290) which should allow more room for network instability.

**Comment by Sequal32** [comment]
The new release 2.5.0 includes this setting.
