### ISSUE TITLE
TBM 930 Client airframe overstressed[BUG]

### ISSUE THREAD

**Issue by Pricelesscrab91** [Sequal32/yourcontrols#74]
**Describe the bug**
With myself as Observer some buttons, for example, Aux Boost pump, and Flight Plan displayed on MFD didn't match with server during start-up. And after approx 1 min taxiing my end would say I've overstressed the aircraft, while server keeps on going. We also noted that as soon as start-up sequence was initiated, both party's prop would start before Starter switch was even activated. On subsequent attempts it was repeated but never in sync between server and observer. 
**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as observer.
2. Follow start-up procedure being executed by server and note differences in which switches are shown as being thrown.
3. Check MFD shows same flight plan and legs.
4. Note if both party's have engine start on its own and if sync'd with same behaviour.
4. Commence taxi or flight and see how far you get. We are both in Australia and flying default airport (YSSY) and default TBM 930.

**Expected behavior**
All switches and actions should be sync'd without one party suffering an overstressed airframe.
**Additional context**
We have relatively poor internet in Australia. I ran a speed-test at my end after 4th failed attempt at start-up and taxi, and was getting 13mbps down and only 2mbps up. Wondering if it could be packet loss, internet speed related (particularly upload speed). 

**__PLEASE ATTACH EVERYONE'S LOGS__**
`Log.txt` can be found in the directory of the .exe file`
We will attempt again tonight and grab logs if same happens.

**Discord**
Your discord name if you're in the YourControl discord server.
Will sign up to Discord.

**Comment by Sequal32** [comment]
Hi! It's recommended you disable crash physics in the realism settings prior to using this program for this exact reason.
