### ISSUE TITLE
Application will not launch [BUG]

### ISSUE THREAD

**Issue by smokedsalmonbagel** [Sequal32/yourcontrols#75]
Firstly - thanks for all the hard work.  Its really great to have a shared cockpit!

**Describe the bug**
I was able to launch the exe a few days ago.  But today I run the application, get a hourglass for a second then nothing.  I have reinstalled, rebooted etc.  The only thing that changed was I setup a HP Reverb WMR headset today.  I looked in log.txt - it was blank. I tried installing webview2 etc. but like I said nothing has changed except a few windows updates and the WMR setup.

**To Reproduce**
The only changes I made were installing a WMR headset - not sure if this would reproduce.  I have another computer which still runs the exe using an Oculus.

**Expected behavior**
Should start

**Additional context**
I also tried without WMR hub running.  I would love to test anything else which might shed some light on this issue.

**__PLEASE ATTACH EVERYONE'S LOGS__**
The log.txt file is blank.

**Comment by Sequal32** [comment]
This is certainly weird... I don't really have an idea what could be causing it. Perhaps you can try looking in the `Administrative Events` in the windows event viewer and see if there's an entry for `YourControls.exe` that might shed some light on the issue. If you're in the discord server we can get together and try to solve this further.

**Comment by smokedsalmonbagel** [comment]
There are two events for the application - not sure how much help they will be:
```
Faulting application name: YourControls.exe, version: 2.4.1.0, time stamp: 0x60045a31
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x29d0
Faulting application start time: 0x01d703c2dccaa86a
Faulting application path: C:\Users\admin\AppData\Roaming\YourControls\YourControls.exe
Faulting module path: unknown
Report Id: 8768b030-71c4-41b4-8268-db5da1a813de
Faulting package full name: 
Faulting package-relative application ID: 
```
Then:
```
Fault bucket 1626940391768773398, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: YourControls.exe
P2: 2.4.1.0
P3: 60045a31
P4: StackHash_921a
P5: 0.0.0.0
P6: 00000000
P7: PCH_84_FROM_unknown+0x0000000000000000
P8: c0000005
P9: 0000000000000008
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AF4.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2B34.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2B35.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2B42.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2B53.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_YourControls.exe_8652fab9c622e31219eafb3d25b21f0e3dcb11_e996a227_b5284d09-e202-4383-b764-ca16227f9870

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8768b030-71c4-41b4-8268-db5da1a813de
Report Status: 268435456
Hashed bucket: f7e9465fc221c5d6e6940daa9a1cd316
Cab Guid: 0
```

What is the best way to reset the state of the install?  Is there anything else I can try besides the uninstall/install option?

**Comment by Sequal32** [comment]
Discussed this in Discord - problem assumed to be with vcredist not being installed correctly.

**Comment by smokedsalmonbagel** [comment]
The only way I was able to resolve this was to roll back windows with windows restore.  👻
