### ISSUE TITLE
[BUG] Chaning QNH setting of altimeter causes partner's plane to float

### ISSUE THREAD

**Issue by foxmike80** [Sequal32/yourcontrols#80]
**Describe the bug**
Under certain circumstances, changing the altimeter setting (qnh) can cause the actual altitude of the partner plane to increase.
Tested in A320X mod.

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Spawn at gate
2. Transfer control to client
3. Client turn Altimeter knob to increase QNH; observe altimeter showing a higher altitude
4. Observe server/host plane begin to float
5. When swapping controls again, client's plane takes position of server's plane and both crash

**Expected behavior**
It looks like YourControls syncs the altitude as shown in the altimeter instead of syncing the actual altitude of the plane.

**Additional context**

**__PLEASE ATTACH EVERYONE'S LOGS__**
`Log.txt` can be found in the directory of the .exe file`

**Discord**
foxmike1080

**Comment by Sequal32** [comment]
Oops fix one thing break another... a hotfix is out now.
