### ISSUE TITLE
[BUG] Client disconnected. Could not connect to the YourControl gauge

### ISSUE THREAD

**Issue by Flusinerd** [Sequal32/yourcontrols#91]
**Describe the bug**
On conncting with server ( Cloud P2P ):
Client disconnected. Reason: Could not connect to the YourControls gauge. Do you have the community package installed correctly?

**To Reproduce**
Start YourControl.
Connect to other person hosting.

**Expected behavior**
Be able to connect to other server

**Additional context**
Cleared out the Community Folder, then uninstalled and reinstalled YourControls via the installer.
Issue still persists.

There was an issue during insallation (still had yourControls running) but after closing it and then uninstalling, it worked without any errors.

**__PLEASE ATTACH EVERYONE'S LOGS__**
`Log.txt` can be found in the directory of the .exe file`

**Discord**
N/A
[log Client (Error).txt](https://github.com/Sequal32/yourcontrols/files/6124723/log.Client.Error.txt)
[log (server).txt](https://github.com/Sequal32/yourcontrols/files/6124725/log.server.txt)

**Comment by Sequal32** [comment]
MSFS issue not loading the community package in. Try restarting the simulator without reinstalling.

**Comment by Herculesfo** [comment]
''MSFS issue not loading the community package in. Try restarting the simulator without reinstalling.'' tried that several times, no luck.

**Comment by lakryh** [comment]
i am getting this error as well

**Comment by CptBlondBeard** [comment]
Same, have followed the Known Issues fix instructions on the discord multiple times and still getting the issue.

**Comment by Sequal32** [comment]
Please try the newest version of 2.5.7 and see if that fixes the issue since the gauge was updated.
