### ISSUE TITLE
Aerosoft CRJ 700

### ISSUE THREAD

**Issue by babyaby1** [Sequal32/yourcontrols#92]
Hi This is not a bug but rather a request - is there any chance you could add the new Aerosoft CRJ 700 into your fleet for Shared Cockpit (Your Controls)?
Thanks

**Comment by MoritzT** [comment]
+1 to that! Happy to sponsor a copy if that's what it takes

**Comment by Sequal32** [comment]
Currently working on it!

**Comment by meochan913** [comment]
> Currently working on it!

Thank you so much man! I really wish there could be a relatively easier way to let ppl get involved and participate in helping creating the yaml profiles for new aircrafts.

**Comment by Sequal32** [comment]
Me too! Currently rewriting a bunch of stuff that will eventually allow me to make a semi-automatic way of creating definitions that should be relatively simple for anyone to help out in the future.

**Comment by meochan913** [comment]
> Me too! Currently rewriting a bunch of stuff that will eventually allow me to make a semi-automatic way of creating definitions that should be relatively simple for anyone to help out in the future.

Yeah man!! We would all be benefit from that man!

**Comment by Sequal32** [comment]
A beta is out: https://github.com/Sequal32/yourcontrolsinstaller/releases/download/beta/installer.zip

**Comment by meochan913** [comment]
YAAAAS Thank you man!

**Comment by Platohjwang** [comment]
THXXXXXXXXXXX

**Comment by Sequal32** [comment]
New beta out that syncs a bunch more stuff. Autopilot selectors are very very finicky so you need to go slow when using them. Same link for install.

**Comment by Platohjwang** [comment]
THANK YOU! but it points back to v2.5.6? didn't see the beta sign there

**Comment by Sequal32** [comment]
Oops... updating it now

**Comment by Platohjwang** [comment]
thx for all ur efforts. Still, it is really hard to synchronize alt speed etc even we tried to slow down.

**Comment by Sequal32** [comment]
Really limited in functionality since knobs are very annoying to sync, but this is now added in 2.5.7.
