### ISSUE TITLE
mixMugz TBM 930 Project

### ISSUE THREAD

**Issue by guifarias31** [Sequal32/yourcontrols#93]
Hi there! Great project! It would be nice to add support to mixMugz TBM 930 mod: https://github.com/mixMugz/msfs_tbm930_project
Thanks for your work!

**Comment by Sequal32** [comment]
A beta is out that includes this: https://github.com/Sequal32/yourcontrolsinstaller/releases/download/beta/installer.zip

**Comment by guifarias31** [comment]
Thanks! Where can I normally find the beta versions? Is there a .zip version as well, not instaler?

**Comment by Sequal32** [comment]
Here you go: https://github.com/Sequal32/yourcontrols/releases/download/vbetabase/YourControls.zip

**Comment by Sequal32** [comment]
Added support in 2.5.7.
