### ISSUE TITLE
[BUG] A320NX most buttons not synced

### ISSUE THREAD

**Issue by Road-to-Hell9** [Sequal32/yourcontrols#94]
**Describe the bug**
A320NX most buttons not synced since update on the 21/03/2021

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.

**Expected behavior**
A clear and concise description of what you expected to happen. For example: Navigation lights are synced between all clients.

**Additional context**

**__PLEASE ATTACH EVERYONE'S LOGS__**
[log.txt](https://github.com/Sequal32/yourcontrols/files/6178327/log.txt)

**Comment by Sequal32** [comment]
You selected the wrong config file.
```
18:41:47 [INFO] [DEFINITIONS] JPLogistics_C152X.yaml aircraft config selected.
18:41:47 [INFO] [SIM] Connected to SimConnect.
18:41:47 [INFO] [DEFINITIONS] Loaded and mapped 180 aircraft vars, 37 local vars, and 153 events
18:41:47 [INFO] [DEFINITIONS] JPLogistics_C152X.yaml loaded successfully.
```
To use the A32NX, select the `FlyByWire_A32NX.yaml` file under `Active Aircraft`.

**Comment by Road-to-Hell9** [comment]
Really sorry
