### ISSUE TITLE
Trottle not syncing properly [BUG]

### ISSUE THREAD

**Issue by 0Jumpero** [Sequal32/yourcontrols#98]
**Describe the bug**
My and my friend are using A32NX mod in experimental version, which includes new thrust logic. We have noticed trottle lever doesn't sync between us, instead it seems that it syncs to engine speed, i.e. when flying level with trottle lever on CLB as captain, FO's trottle lever is sometimes below or above CLB. When descending, lever goes even lower, while ascending lever goes up to TOGA (just as N1 of the engines goes up or down).

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Fly level with FO and observe trottle and ECAM.
2. Ascend/Descend and as N1 goes up/down FO's trottle lever moves .

**Expected behavior**
Trottle position should be synced, not N1 to FO's trottle.

**Additional context**
On PFD, even if plane flies level, V/S shows max climb or max descend value.

**LOGS**
[Captain log.txt](https://github.com/Sequal32/yourcontrols/files/6231725/Captain.log.txt)
[FO log.txt](https://github.com/Sequal32/yourcontrols/files/6231729/FO.log.txt)

**Comment by Sequal32** [comment]
Will be looking for a solution to this when I find the time :)

**Comment by Beatinio** [comment]
> Will be looking for a solution to this when I find the time :)

This would be very nice. thanks gor your work.

**Comment by Sequal32** [comment]
New release out (2.5.13) that address this.
