### ISSUE TITLE
Client disconnected. Reason: Could not connect to session.  

### ISSUE THREAD

**Issue by Swampfox87** [Sequal32/yourcontrols#99]
I was using YourControls software correctly until now, that shows this message when I try to host a server on both P2P and Cloud "Client disconnected. Reason: Could not connect to session."

My friend's software was working good, he could host normally, also when I tried to join his server I got the same message, and could't use it, i have my Antivirus off and firewall, I don't know what can I do to fix this.

Thanks
 PD: I tried reinstalling many times today and still the same, it was working yesterday.
![YC](https://user-images.githubusercontent.com/64748453/113241299-07d20c80-9274-11eb-9662-eeefcb791c0a.png)

**Comment by Sequal32** [comment]
Weird, I manually restarted the cloud server to see if there was some issue with having it up for more than a month without a restart so see if that fixes the issue.

**Comment by Swampfox87** [comment]
Not working, I don't know what happened tbh, I cannot connect for some reason. It does not work with the 3 host options.

![YC](https://user-images.githubusercontent.com/64748453/113300366-768a8680-92c3-11eb-9c6b-b6b2aebce6e1.png)

**Comment by Sequal32** [comment]
Can't reproduce this... try switching to another network like a mobile network if you can, or maybe try the direct option and port forward.
